# Product Configuration: Teamspec Viewer
product:
  id: "teamspec-viewer"
  name: "Teamspec Viewer"
  prefix: "TSV"
  description: |
    A read-only browser application for navigating and viewing TeamSpec 4.0 
    documentation artifacts. Provides role-specific dashboards (BA, FA) for 
    browsing products, projects, features, feature-increments, epics, and 
    stories. Highlights {TBD} markers for quick identification of incomplete 
    documentation.
  status: active  # active, deprecated, archived
  
  # List of projects currently modifying this product
  active_projects:
    - teamspecviewermvp
